{
 "title": "Uitsmijter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uitsmijter Dashboard",
   "type": "text",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "options": {
    "content": "<h1>Uitsmijter Metrics</h1>\n\n<img height=\"300px\" src=\"https://nightly.uitsmijter.io/images/eierpaar-mit-augen.png\"></img>\n           "
   }
  },
  {
   "title": "Tenants",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(uitsmijter_tenants_count{kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(uitsmijter_clients_count{kubernetes_namespace=~\"$namespace\"})",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Redis Connections",
   "type": "stat",
   "gridPos": { "h": 11, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(redistack_totalconnectioncount{kubernetes_namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Login attempts (per $interval)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(increase(uitsmijter_login_attempts_count{tenant=~\".+\", kubernetes_namespace=~\"$namespace\"}[$interval])) by (tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  { "title": "Logins", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Successful logins (per $interval)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(uitsmijter_login_success{tenant=~\".+\", kubernetes_namespace=~\"$namespace\"}[$interval])) by (tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Failed logins (per $interval)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(uitsmijter_login_failure{tenant=~\".+\", kubernetes_namespace=~\"$namespace\"}[$interval])) by (tenant)",
     "legendFormat": "{{ tenant }}"
    }
   ]
  },
  {
   "title": "Login Success vs Failure",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(increase(uitsmijter_login_success{tenant=~\".+\", kubernetes_namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(uitsmijter_login_failure{tenant=~\".+\", kubernetes_namespace=~\"$namespace\"}[$__range]))",
     "legendFormat": "Failure"
    }
   ]
  },
  { "title": "OAuth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Grant Types (Success)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(uitsmijter_oauth_success{kubernetes_namespace=~\"$namespace\"}) by (grant_type)",
     "legendFormat": "{{ grant_type }}"
    }
   ]
  },
  {
   "title": "Grant Types (Failure)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(uitsmijter_oauth_failure{kubernetes_namespace=~\"$namespace\"}) by (grant_type)",
     "legendFormat": "{{ grant_type }}"
    }
   ]
  },
  {
   "title": "Clients  (Success)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(uitsmijter_oauth_success{kubernetes_namespace=~\"$namespace\"}) by (tenant, client)",
     "legendFormat": "{{tenant}}: {{ client }}"
    }
   ]
  },
  {
   "title": "Clients  (Failure)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(uitsmijter_oauth_failure{kubernetes_namespace=~\"$namespace\"}) by (tenant, client)",
     "legendFormat": "{{tenant}}: {{ client }}"
    }
   ]
  },
  { "title": "Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Known Tokens over $interval",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(uitsmijter_token_stored_count{kubernetes_namespace=~\"$namespace\"}[$interval]))"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds{status=~\".+\", kubernetes_namespace=~\"$namespace\", path!~\".*/(health|metrics).*\"}[$__range])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Top 5 Request Paths",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(increase(http_request_duration_seconds{path=~\".+\", kubernetes_namespace=~\"$namespace\", path!~\".*/(health|metrics).*\"}[$__range])) by (path))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(increase(http_request_duration_seconds_count{path=~\".+\", kubernetes_namespace=~\"$namespace\", path!~\".*/(health|metrics).*\"}[$__range])) by (method, path))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Requests Duration by path",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(avg(rate(http_request_duration_seconds_sum{kubernetes_namespace=~\"$namespace\", path!~\".*/health.*\"}[$__range])) by (method, path) / avg(rate(http_request_duration_seconds_count{kubernetes_namespace=~\"$namespace\", path!~\".*/health.*\"}[$__range])) by (method, path)) > 0",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Request duration over $interval (avg)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{path=~\".+\", kubernetes_namespace=~\"$namespace\"}[$interval])) by(method, path) / sum(rate(http_request_duration_seconds_count{path=~\".+\", kubernetes_namespace=~\"$namespace\"}[$interval])) by(method, path)",
     "legendFormat": "{{method}} {{ path }}"
    }
   ]
  }
 ]
}