disabled_rules:
  - private_over_fileprivate
  - implicit_getter
  - class_delegate_protocol
  - syntactic_sugar

analyzer_rules:
  - unused_import
  - unused_declaration
  - capture_variable

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - number_separator
  - anonymous_argument_in_multiline_closure
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_is_empty
  - discouraged_none_name
  - empty_collection_literal
  - empty_count
  - empty_xctest_method
  - file_name_no_space
  - force_unwrapping
  - unavailable_function
  - unowned_variable_capture
  - yoda_condition

included:
  - Sources
  - Tests

excluded:

# configurable rules
force_cast: warning
force_try:
  severity: warning

nesting:
  type_level: 3
  function_level: 5
  check_nesting_in_closures_and_statements: true
  always_allow_one_type_in_functions: true

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 90
  error: 120

closure_body_length:
  warning: 60
  error: 80

large_tuple:
  warning: 4
  error: 6

number_separator:
  minimum_length: 5

type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: # excluded via string
  allowed_symbols: [ "" ] # these are allowed in type names

identifier_name:
  min_length: 3 # only error
  max_length: # warning and error
    warning: 30
    error: 50
  excluded: # excluded via string array
    - id
    - in
    - fn
    - ms
    - i
  allowed_symbols: [ "_" ]
  validates_start_with_lowercase: warning

reporter: "codeclimate" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
