name: "Helm"
description: "Build helm packages"
author: "aus der Technik | Uitsmijter"


inputs:
  deploy_key:
    description: "Deploy key for the charts repository"
    required: true

runs:
  using: composite
  steps:
    - name: Build helm release
      shell: bash
      run: ./tooling.sh helm
    - name: Store helm release package
      uses: actions/upload-artifact@v3
      with:
        name: helm-package
        path: |
          ./Deployment/Release/**-**.tgz
    - name: Create charts dir
      shell: bash
      run: |
        mkdir ./charts
        tar -xvf ./Deployment/Release/uitsmijter-**.tgz -C ./charts --strip-components 1
    - name: Deploy to external repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ inputs.deploy_key }}
      with:
        source-directory: charts/
        destination-github-username: $GITHUB_ACTOR
        destination-repository-name: uitsmijter/charts
        user-email: "$GITHUB_ACTOR@users.noreply.github.com"
        target-branch: "main"
        commit-message: "${{ github.ref_name }}"
        create-target-branch-if-needed: true
