# Goat Interceptor page
---
kind: Pod
apiVersion: v1
metadata:
  name: goat-webserver
  namespace: cheese
  labels:
    app: goat-webserver

spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: content
          mountPath: "/usr/share/nginx/html"
          readOnly: true
        - name: config-templates
          mountPath: "/etc/nginx/templates"
          readOnly: true

  volumes:
    - name: content
      configMap:
        name: goat-content
    - name: config-templates
      configMap:
        name: nginx-goat-templates

---
kind: Service
apiVersion: v1
metadata:
  name: goat-webserver
  namespace: cheese

spec:
  selector:
    app: goat-webserver

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-goat-templates
  namespace: cheese
data:
  default.conf.template: |
    server {
      listen        80;
      server_name   goat.example.com;
      location / {
        root   /usr/share/nginx/html;
        index  /index.html;
        add_header Cache-Control no-cache;
        try_files $uri $uri.html $uri/index.html;
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: goat-content
  namespace: cheese
data:
  index.html: |
    <html>
    <head>
        <title>Goats</title>
        <meta http-equiv="Pragma" content="no-cache"/>
        <meta http-equiv="Cache-Control" content="no-cache"/>
    </head>
    <body>
    <h1 class="headline">Goat Cheese on a Uitsmijter</h1>
    <p>
        This is very unusual and should be avoided. Rather use Gauda.
    </p>
    <footer>
        <a href="//login.example.com/logout?post_logout_redirect_uri=//goat.example.com">logout</a>
    </footer>
    </body>
    </html>

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: goat-webserver
  namespace: cheese
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: uitsmijter-forward-auth@kubernetescrd

spec:
  tls:
    - secretName: example.com
  rules:
    - host: goat.example.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: goat-webserver
                port:
                  number: 80
