# Cookbooks Interceptor page
---
kind: Pod
apiVersion: v1
metadata:
  name: glair-webserver
  namespace: egg
  labels:
    app: glair-webserver

spec:
  containers:
    - name: nginx
      image: nginx

      volumeMounts:
        - name: content
          mountPath: "/usr/share/nginx/html"
          readOnly: true
        - name: config-templates
          mountPath: "/etc/nginx/templates"
          readOnly: true

  volumes:
    - name: content
      configMap:
        name: glair-content
    - name: config-templates
      configMap:
        name: glair-nginx-config-templates

---
kind: Service
apiVersion: v1
metadata:
  name: glair-webserver
  namespace: egg

spec:
  selector:
    app: glair-webserver

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glair-nginx-config-templates
  namespace: egg
data:
  default.conf.template: |
    server {
      listen        80;
      server_name   glair.egg.example.com;
      location / {
        root   /usr/share/nginx/html;
        index  index.html;
        add_header Cache-Control no-cache;
        try_files $uri $uri.html $uri/index.html;
      }
    }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: glair-content
  namespace: egg
data:
  index.html: |
    <html>
    <head>
        <title>Glair</title>
        <meta http-equiv="Pragma" content="no-cache"/>
        <meta http-equiv="Cache-Control" content="no-cache"/>
    </head>
    <body>
    <h1 class="headline">Information about yolk</h1>
    <p>
        Pale and glistening, the glair stretches like ghostly silk, a trembling veil of quiet alchemy. It catches the light in 
        wavering ribbons, a breath suspended between liquid and air, whispering secrets of structure and lift. In the stillness, 
        it waits—pliant, unshaped—until heat or motion calls it forth, coaxing it into peaks that gleam like moonlit foam or 
        firming it into something tender, translucent, whole. An unseen architect, it binds, it lifts, it seals—delicate yet 
        unyielding, a silver thread weaving through the fabric of creation.
    </p>

---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: glair-webserver
  namespace: egg
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: uitsmijter-forward-auth@kubernetescrd

spec:
  tls:
    - secretName: egg.example.com
  rules:
    - host: glair.egg.example.com
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: glair-webserver
                port:
                  number: 80
