{{ if .Values.installCRD }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tenants.uitsmijter.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: uitsmijter.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                hosts:
                  type: array
                  items:
                    type: string
                    minItems: 1
                informations:
                  type: object
                  properties:
                    imprint_url:
                      type: string
                    privacy_url:
                      type: string
                    register_url:
                      type: string
                interceptor:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    domain:
                      type: string
                    cookie:
                      type: string
                templates:
                  type: object
                  description: s3 bucket config for tempalte files
                  properties:
                    access_key_id:
                      type: string
                    secret_access_key:
                      type: string
                    host:
                      type: string
                    bucket:
                      type: string
                    path:
                      type: string
                      default: /
                    region:
                      type: string
                      default: us-east-1
                  required:
                    - access_key_id
                    - secret_access_key
                    - host
                    - bucket
                providers:
                  type: array
                  items:
                    type: string
                    minItems: 1
                silent_login:
                  type: boolean
              required:
                - hosts
                - providers

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: tenants
    # singular name to be used as an alias on the CLI and for display
    singular: tenant
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: Tenant
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - tenant
{{ end }}
