---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ include "uitsmijter.namespace" . }}
  name: uitsmijter-authserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: uitsmijter-authserver

  minReplicas: 1
  maxReplicas: 3

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
