---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "uitsmijter.namespace" . }}
  name: jwt-secret
  annotations:
    kubed.appscode.com/sync: jwt-secret/sync=true
stringData:
  JWT_SECRET: {{ .Values.jwtSecret | default (randAlphaNum 64) | quote }}
