name: "Clean Cache"
description: "Cleans the cache for this run"
author: "aus der Technik | Uitsmijter"

inputs:
  volume:
    description: 'Volume name to cache'
    required: true
    default: ''

runs:
  using: composite
  steps:
    - name: Cache Volumes Read .build
      uses: ./.github/actions/docker-volume-cache/read
      with:
        volume: ${{ inputs.volume }}

    - name: Remove Files
      env:
        VOLUME: ${{ inputs.volume }}
      shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
      run: |
        docker run --rm -ti -v ${VOLUME}:/data ubuntu bash -c 'rm -rf /data/*' 

    - name: Cache Volumes Write .build
      uses: ./.github/actions/docker-volume-cache/write
      with:
        volume: uitsmijter_build
    - name: Cache Volumes Write npm
      uses: ./.github/actions/docker-volume-cache/write
      with:
        volume: ${{ inputs.volume }}
