---
apiVersion: "uitsmijter.io/v1"
kind: Client
metadata:
  name: uitsmijter-client
spec:
  ident: 2cec55ff-e7bd-456a-9241-311357d5d9eb
  tenantname: uitsmijter/uitsmijter-tenant
  redirect_urls:
    - 'https?://(.*\.)?localhost(:8080)?/.*'
  grant_types:
    - password
    - authorization_code
    - refresh_token
  scopes:
    - access
  referrers:
    - 'https?://(.*\.)?localhost(:8080)?/.*'
  isPkceOnly: false

---
apiVersion: "uitsmijter.io/v1"
kind: Client
metadata:
  name: bnbc
spec:
  ident: 679a09cf-99ae-4a4b-bffb-5c2da6b4bf8f
  tenantname: uitsmijter/bnbc
  redirect_urls:
    - 'https?://(.*\.)?bnbc\.example(:8080)?/.*'

---
apiVersion: "uitsmijter.io/v1"
kind: Client
metadata:
  name: ham
spec:
  ident: 9a9bd8a1-70ca-482b-a753-20b87a661cf2
  tenantname: uitsmijter/ham
  redirect_urls:
    - 'https?://(.*\.)?ham.test(:8080)?/.*'
