apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - ns.yml
  - crd.yml
  - rbac.yml
  - traefik.yml
secretGenerator:
  - name: default-certificate
    files:
      - certificates/tls.crt
      - certificates/tls.key
generatorOptions:
  disableNameSuffixHash: true
