---
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3config
data:
  # https://github.com/seaweedfs/seaweedfs/wiki/Amazon-S3-API#s3-authentication
  config.json: |
    {
      "identities": [
        {
          "name": "admin",
          "credentials": [
            {
              "accessKey": "admin",
              "secretKey": "adminSecretKey"
            }
          ],
          "actions": [
            "Read",
            "Write",
            "List",
            "Tagging",
            "Admin"
          ]
        },
        {
          "name": "test",
          "credentials": [
            {
              "accessKey": "test",
              "secretKey": "testsecret"
            }
          ],
          "actions": [
            "Read:bucketname",
            "Write:bucketname",
            "List:bucketname",
            "Tagging:bucketname",
            "Admin:bucketname"
          ]
        },
        {
          "name": "anonymous",
          "actions": [
            "Read:public"
          ]
        }
      ]
    }
