name: Open PR
on:
  pull_request:
    types:
      - opened

jobs:
  notify_mattermost:
    name: Notify Mattermost
    permissions:
      contents: read
      statuses: read
      actions: read
      repository-projects: read

    if: always()
    uses: uitsmijter/workflows/.github/workflows/pullrequest-mattermost.yaml@v1.0.5
    secrets:
      WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK_BUILD }}
