name: Release Candidate
on:
  push:
    branches:
      - release/*


env:
  STORE_ARTEFACTS: true
  RUN_LINTER: false
  RUN_UNITTESTS: false
  RUN_BUILD: true
  RUN_E2ETESTS: false
  RUN_HELM: true
  RUN_PUBLISH: true

jobs:
  # Lint
  lint:
    name: Run Linter checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: ./.github/actions/step-lint
        if: ${{ env.RUN_LINTER != 'false' }}

  unittest:
    name: Run UnitTest
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - uses: ./.github/actions/step-unittest
        if: ${{ env.RUN_UNITTESTS != 'false' }}

  build:
    name: Build Uitsmijter
    runs-on: ubuntu-latest
    needs:
      - lint
      - unittest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          lfs: true
      - uses: ./.github/actions/step-build
        if: ${{ env.RUN_BUILD != 'false' }}
        with:
          release: true

  # End-2-End
  e2etest:
    name: Run E2E-Tests
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          lfs: true

      - uses: ./.github/actions/step-e2e
        if: ${{ env.RUN_E2ETESTS != 'false' }}
        with:
          dirty: false
          fast: true

  build-helm:
    runs-on: ubuntu-latest
    needs:
      - e2etest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        if: ${{ env.RUN_HELM != 'false' }}
      - uses: ./.github/actions/step-helm
        if: ${{ env.RUN_HELM != 'false' }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs:
      - build-helm
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        if: ${{ env.RUN_PUBLISH != 'false' }}
      - uses: ./.github/actions/step-publish
        if: ${{ env.RUN_PUBLISH != 'false' }}
        with:
          tag: ${{ github.ref_name }}

  # Notify
  notify_mattermost:
    name: Notify Mattermost
    permissions:
      contents: read
      statuses: read
      actions: read
      repository-projects: read
    needs:
      - publish
    if: always()
    uses: uitsmijter/workflows/.github/workflows/builds-mattermost.yaml@main
    secrets:
      WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK_BUILD }}

  notify_mastodon:
    name: Notify Mastodon
    permissions:
      contents: read
      statuses: read
      actions: read
      repository-projects: read
    needs:
      - publish
    if: always()
    uses: uitsmijter/workflows/.github/workflows/builds-mastodon.yaml@main
    secrets:
      MASTODON_URL: ${{ secrets.MASTODON_BUILDS_URL }}
      MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_BUILDS_TOKEN }}

  notify_release:
    name: Notify Release Mastodon
    permissions:
      contents: read
      statuses: read
      actions: read
      repository-projects: read
    needs:
      - publish
    uses: uitsmijter/workflows/.github/workflows/release-mastodon.yaml@main
    secrets:
      MASTODON_URL: ${{ secrets.MASTODON_RELEASE_URL }}
      MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_RELEASE_TOKEN }}
